#ifndef SPACEINVADERS_ENUMS_H
#define SPACEINVADERS_ENUMS_H


enum BONUS_TYPE{
    SPEED,LIFE, POINTS
};

enum ENEMY_TYPE{
    OCTOPUS,CRAB,SQUID
};

enum PLAYER_ACTION{
    MOVE_LEFT, MOVE_RIGHT, PLAYER_SHOOT, NONE
};

enum SOUND_TYPE{
    SHOOT, HIT, INVADER_KILLED
};
enum SPRITE{
    PLAYERSHIP,ENEMY_BIG,ENEMY_MEDIUM,ENEMY_SMALL,INVADER_DEATH,UFO
};
#endif //SPACEINVADERS_ENUMS_H
